name: Build RISC-V GCC

on: [push, pull_request]

jobs:
    build_riscv_gcc:
      runs-on: ubuntu-20.04
      #container:
      #  image: modm/riscv-gcc-prerequisites:latest

      steps:

      - name: Setup
        run: |
         sudo apt-get update
         sudo apt-get upgrade -y
         sudo apt-get install -y autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev git

      - name: Git Clone
        run: git clone --recursive --jobs 16 https://github.com/riscv/riscv-gnu-toolchain

      - name: Configure
        run: (cd riscv-gnu-toolchain && ./configure --prefix=/opt/riscv-gcc)

      - name: Build
        run: (cd riscv-gnu-toolchain && make -j4)

      - name: Test
        run: |
         /opt/riscv-gcc/bin/riscv64-unknown-elf-g++ --version
         echo "int main() { return 0;}" > main1.cpp
         /opt/riscv-gcc/bin/riscv64-unknown-elf-g++ main1.cpp

      - name: Gzip
        run: tar cjf riscv-gcc.tar.bz2 -C /opt riscv-gcc

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: riscv-gcc.tar.bz2
          path: riscv-gcc.tar.bz2
